
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwuvstrzbskwfsxxizxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dXZzdHJ6YnNrd2ZzeHhpenhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MjY4MzgsImV4cCI6MjA1NzUwMjgzOH0.jxMtv9dA2B_C_qsHxDALurC4I6xpq4b7gtCur-SPKd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  }
});
